BaseProjectTemplate/App.Web/ViewModels/Role/RoleAddVM.cs
using App.Share.Consts;
using App.Web.WebConfig;
using App.Shared.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Web.ViewModels.Role
{
	public class RoleAddVM
	{
		[AppRequired]
		[AppMaxLength(DB.AppRole.NAME_LENGTH)]
		public string Name { get; set; }
		
		[AppRequired]
		[AppMaxLength(DB.AppRole.DESC_LENGTH)]
		public string Desc { get; set; }

		// Chuỗi chứa permissionId, phân tách bởi dấu phẩy
		[AppRequired(ErrorMessage = VM.RoleVM.PERMISSION_IDS_REQUIRED_ERR_MESG)]
		[AppRegex(VM.RoleVM.PERMISSION_IDS_REGEX, ErrorMessage = VM.RoleVM.PERMISSION_IDS_REGEX_ERR_MESG)]
		public string PermissionIds { get; set; }
	}
}

BaseProjectTemplate/App.Web/ViewModels/Role/RoleDeleteVM.cs
using App.Web.WebConfig;
using App.Shared.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Web.ViewModels.Role
{
	public class RoleDeleteVM
	{
		public RoleDeleteVM()
		{
			AppUsers = new List<RoleDeleteVM_User>();
		}
		public int Id { get; set; }

		[AppRequired(ErrorMessage = VM.RoleVM.NEWID_REQUIRED_ERR_MESG)]
		public int NewId { get; set; }
		public string Name { get; set; }
		public string Desc { get; set; }
		public DateTime? CreatedDate { get; set; }
		public DateTime? UpdatedDate { get; set; }

		public List<RoleDeleteVM_User> AppUsers { get; set; }
	}

	public class RoleDeleteVM_User
	{
		public int Id { get; set; }
		public string Username { get; set; }
		public DateTime? DeletedDate { get; set; }
	}
}

BaseProjectTemplate/App.Web/ViewModels/Role/RoleEditVM.cs
using App.Share.Consts;
using App.Web.WebConfig;
using App.Shared.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Web.ViewModels.Role
{
	public class RoleEditVM
	{
		public int Id { get; set; }
		[AppRequired]
		[AppMaxLength(DB.AppRole.NAME_LENGTH)]
		public string Name { get; set; }
		[AppRequired]
		[AppMaxLength(DB.AppRole.DESC_LENGTH)]
		public string Desc { get; set; }

		// Chuỗi chứa permissionId hiện tại, phân tách bởi dấu phẩy
		[AppRegex(VM.RoleVM.PERMISSION_IDS_REGEX, ErrorMessage = VM.RoleVM.PERMISSION_IDS_REGEX_ERR_MESG)]
		public string PermissionIds { get; set; }

		// Chuỗi chứa permissionId sẽ được xóa, phân tách bởi dấu phẩy
		public string DeletedPermissionIds { get; set; }

		// Chuỗi chứa permissionId được thêm mới, phân tách bởi dấu phẩy
		public string AddedPermissionIds { get; set; }
	}
}

BaseProjectTemplate/App.Web/ViewModels/Role/RoleListItemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace App.Web.ViewModels.Role
{
	public class RoleListItemVM : ListItemBaseVM
	{
		public string Name { get; set; }
		public string Desc { get; set; }
		public DateTime? CreatedDate { get; set; }
	}
}

BaseProjectTemplate/App.Web/Components/ListRole/ListRoleViewComponent.cs
using App.Data.Entities;
using App.Data.Repositories;
using App.Web.ViewModels.Role;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace App.Web.Components.ListRole
{
	public class ListRoleViewComponent : ViewComponent
	{
		readonly GenericRepository repository;
		public ListRoleViewComponent(GenericRepository _db)
		{
			repository = _db;
		}
		public async Task<IViewComponentResult> InvokeAsync(int? seletetedId, IEnumerable<int> excludeIds)
		{
			var data = await repository
					.GetAll<AppRole>(where: r => excludeIds == null || excludeIds.Any() && !excludeIds.Contains(r.Id))
					.ToListAsync();
			ViewBag.SelectedId = seletetedId;
			return View(data);
		}
	}
}

BaseProjectTemplate/App.Web/Components/Permission/PermissionViewComponent.cs
using App.Data.Entities;
using App.Data.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace App.Web.Components.Permission
{
	public class PermissionViewComponent : ViewComponent
	{
		readonly GenericRepository repository;
		public PermissionViewComponent(GenericRepository _repository)
		{
			repository = _repository;
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			var data = await repository
							.GetAllMst<MstPermission>()
							.AsEnumerable()
							.GroupBy(x => x.GroupName)
							.ToListAsync();
			return View(data);
		}
	}
}

BaseProjectTemplate/App.Web/Controllers/RoleController.cs
using App.Data.Entities;
using App.Data.Repositories;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using App.Web.Common;
using App.Web.ViewModels.Role;
using App.Share.Extensions;
using AutoMapper.QueryableExtensions;
using App.Web.WebConfig;
using Microsoft.EntityFrameworkCore;
using App.Share.Consts;

namespace App.Web.Controllers
{
	public class RoleController : AppControllerBase
	{
		readonly GenericRepository _repository;
		public RoleController(GenericRepository repository, IMapper mapper) : base(mapper)
		{
			_repository = repository;
		}

		[AppAuthorize(AuthConst.AppRole.VIEW_LIST)]
		public async Task<IActionResult> Index(int page = 1, int size = DEFAULT_PAGE_SIZE)
		{
			var data = (await _repository
				.GetAll<AppRole, RoleListItemVM>(AutoMapperProfile.RoleIndexConf)
				.ToPagedListAsync(page, size))
				.GenRowIndex();
			return View(data);
		}

		[AppAuthorize(AuthConst.AppRole.CREATE)]
		public IActionResult Create() => View();

		[HttpPost]
		[AppAuthorize(AuthConst.AppRole.CREATE)]
		public async Task<IActionResult> Create(RoleAddVM model)
		{
			if (model.PermissionIds == null)
			{
				SetErrorMesg(MODEL_STATE_INVALID_MESG);
				return View(model);
			}
			var arrIdPermission = model.PermissionIds.Split(',');

			var role = new AppRole
			{
				Name = model.Name,
				Desc = model.Desc
			};
			try
			{
				await _repository.AddAsync(role);
				foreach (var item in arrIdPermission)
				{
					var idPer = Convert.ToInt32(item);
					role.AppRolePermissions.Add(new AppRolePermission
					{
						MstPermissionId = idPer
					});
				}
				await _repository.AddAsync(role.AppRolePermissions);
				SetSuccessMesg($"Thêm vai trò [{role.Name}] thành công");
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				LogException(ex);
				return View();
			}
		}

		[AppAuthorize(AuthConst.AppRole.UPDATE)]
		public async Task<IActionResult> Edit(int? id)
		{
			if (!id.HasValue)
			{
				SetErrorMesg(PAGE_NOT_FOUND_MESG);
				return RedirectToAction(nameof(Index));
			}
			var data = await _repository.GetOneAsync<AppRole, RoleEditVM>(id.Value, r => new RoleEditVM
			{
				Id = r.Id,
				Name = r.Name,
				Desc = r.Desc,
				PermissionIds = string.Join(',', r.AppRolePermissions.Select(rp => rp.MstPermissionId)),
			});
			if (data == null)
			{
				SetErrorMesg(PAGE_NOT_FOUND_MESG);
				return RedirectToAction(nameof(Index));
			}
			return View(data);
		}

		[HttpPost]
		[AppAuthorize(AuthConst.AppRole.UPDATE)]
		public async Task<IActionResult> Edit(RoleEditVM model)
		{
			if (!ModelState.IsValid)
			{
				SetErrorMesg(MODEL_STATE_INVALID_MESG, true);
				return RedirectToAction(nameof(Index));
			}
			var role = await _repository.FindAsync<AppRole>(model.Id);
			var curPermisssionIds = _repository
								.GetAll<AppRolePermission>(where: s => s.AppRoleId == role.Id)
								.ToList();
			if (role == null)
			{
				SetErrorMesg(PAGE_NOT_FOUND_MESG);
				return RedirectToAction(nameof(Index));
			}

			// danh sách permission bị xóa khỏi role
			var deletedPermissionIds = model.DeletedPermissionIds.IsNullOrEmpty() ? null : model.DeletedPermissionIds.Split(',').Select(i => Convert.ToInt32(i));
			// danh sách permission được thêm vào role
			var addedPermissionIds = model.AddedPermissionIds.IsNullOrEmpty() ? null : model.AddedPermissionIds.Split(',').Select(i => Convert.ToInt32(i)).OrderBy(i => i);
			// danh sách permission hiện tại
			var rolePermissionIds = curPermisssionIds
								.Where(x => deletedPermissionIds != null && deletedPermissionIds.Contains(x.MstPermissionId))
								.Select(x => x.Id)
								.OrderBy(x => x);
			// nếu xóa hết permission mà không thêm mới thì không cho thêm
			if ((addedPermissionIds == null || !addedPermissionIds.Any()) && deletedPermissionIds != null && rolePermissionIds.SequenceEqual(deletedPermissionIds))
			{
				SetErrorMesg(MODEL_STATE_INVALID_MESG);
				return RedirectToAction(nameof(Edit), new { id = model.Id });
			}

			if (deletedPermissionIds != null && deletedPermissionIds.Any())
			{
				await _repository.HardDeleteAsync<AppRolePermission>(rolePermissionIds);
			}

			if (addedPermissionIds != null && addedPermissionIds.Any())
			{
				var addedRolePermisson = new List<AppRolePermission>();
				foreach (var item in addedPermissionIds)
				{
					addedRolePermisson.Add(new AppRolePermission
					{
						AppRoleId = role.Id,
						MstPermissionId = item
					});
				}
				await _repository.AddAsync(addedRolePermisson);
			}
			role.Name = model.Name;
			role.Desc = model.Desc;
			await _repository.UpdateAsync(role);
			SetSuccessMesg($"Cập nhật vai trò [{role.Name}] thành công");
			return RedirectToAction(nameof(Index));
		}

		[AppAuthorize(AuthConst.AppRole.DELETE)]
		public async Task<IActionResult> Delete(int? id)
		{
			if (!id.HasValue)
			{
				SetErrorMesg(PAGE_NOT_FOUND_MESG);
				return RedirectToAction(nameof(Index));
			}

			var data = await _repository.FindAsync<AppRole, RoleDeleteVM>(id.Value, AutoMapperProfile.RoleDeleteConf);

			if (data == null)
			{
				SetErrorMesg(PAGE_NOT_FOUND_MESG);
				return RedirectToAction(nameof(Index));
			}
			// Xóa không cần xác nhận nếu không có dữ liệu user liên quan
			if (data.AppUsers == null || data.AppUsers.Count == 0)
			{
				await _repository.DeleteAsync<AppRole>(data.Id);
				SetSuccessMesg($"Xóa vai trò [{data.Name}] thành công");
				return RedirectToAction(nameof(Index));
			}

			var userDeletedCount = data.AppUsers.Where(u => u.DeletedDate != null).Count();
			if (userDeletedCount == data.AppUsers.Count)
			{
				await _repository.DeleteAsync<AppRole>(data.Id);
				var users = await _repository.GetAll<AppUser>(where: u => u.AppRoleId == data.Id).ToListAsync();
				// Cập nhật vai trò mới
				users.ForEach(u => u.AppRoleId = null);
				await _repository.UpdateAsync(users);
				SetSuccessMesg($"Xóa vai trò [{data.Name}] thành công");
				return RedirectToAction(nameof(Index));
			}
			// Chỉ hiển thị user chưa bị xóa
			data.AppUsers = data.AppUsers.Where(u => u.DeletedDate == null).ToList();
			return View(data);
		}

		[HttpPost]
		[AppAuthorize(AuthConst.AppRole.DELETE)]
		public async Task<IActionResult> Delete(RoleDeleteVM data)
		{
			if (!ModelState.IsValid)
			{
				SetErrorMesg(MODEL_STATE_INVALID_MESG, true);
				return RedirectToAction(nameof(Index));
			}

			try
			{
				var users = await _repository.GetAll<AppUser>(where: u => u.AppRoleId == data.Id).ToListAsync();
				// Cập nhật vai trò mới
				users.ForEach(u => u.AppRoleId = data.NewId);

				await _repository.BeginTransactionAsync();

				// Cập nhật role mới cho users
				await _repository.UpdateAsync(users);
				// Xóa role cũ
				await _repository.DeleteAsync<AppRole>(data.Id);
				// Lấy thông tin role mới
				var newRolwName = await _repository.GetOneAsync<AppRole, string>(data.NewId, selector: r => r.Name);
				await _repository.CommitTransactionAsync();

				SetSuccessMesg($"Xóa vai trò [{data.Name}] thành công và đã chuyển {users.Count} tài khoản sang vai trò [{newRolwName}]");
				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
				// Rollback
				await _repository.RollbackTransactionAsync();

				SetErrorMesg(EXCEPTION_ERR_MESG);
				LogException(ex);
				return RedirectToAction(nameof(Delete), new { id = data.Id });
			}
		}
	}
}

BaseProjectTemplate/App.Web/Views/Role/Create.cshtml
@model App.Web.ViewModels.Role.RoleAddVM

@{
	ViewData["Title"] = "Thêm vai trò";
}

<form asp-action="Create">
	<div class="row">
		<div class="col-md-12">
			<h5 class="my-3">Thông tin vai trò</h5>
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input asp-for="PermissionIds" class="fake-d-none" />
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Name" class="control-label">Tên vai trò</label>
						<input asp-for="Name" class="form-control" />
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Desc" class="control-label">Mô tả</label>
						<input asp-for="Desc" class="form-control" />
						<span asp-validation-for="Desc" class="text-danger"></span>
					</div>
				</div>
			</div>
		</div>
		<div class="col-12 my-3">
			<h5>Các hành động được phép</h5>
			<span asp-validation-for="PermissionIds" class="text-danger"></span>
		</div>
		@await Component.InvokeAsync("Permission")
	</div>
	<div class="row">
		<div class="col">
			<div class="form-group">
				<button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Lưu</button>
				<button type="reset" class="btn btn-default"><i class="fa fa-undo"></i> Nhập lại</button>
			</div>
		</div>
	</div>
</form>

<partial name="_BackToList" />

@section scripts {
	<script src="~/lib/masonry/masonry.pkgd.min.js"></script>
	<script src="~/js/role/create-edit-role.js" asp-append-version="true"></script>
}

BaseProjectTemplate/App.Web/Views/Role/Delete.cshtml
@model App.Web.ViewModels.Role.RoleDeleteVM

@{
	ViewData["Title"] = $"Xác nhận xóa vai trò [{Model.Name}]";
}
@section head{ 
	<link href="~/lib/bs4-autocomplete/css/bs4-autocomplete.css" rel="stylesheet" />
}

<form asp-action="Delete">
	<div class="row">

		<div class="col-md-4 col-xl-3">
			<h5>Thông tin vai trò</h5>
			<p class="small mb-1">Tạo lúc @Model.CreatedDate.ToDMYHM()</p>
			<p class="small mb-2">Cập nhật lần cuối lúc @Model.UpdatedDate.ToDMYHM()</p>
			<input asp-for="Id" type="hidden" />
			<input asp-for="Name" type="hidden" />
			<div class="form-group">
				<label>Tên vai trò</label>
				<input class="form-control" readonly value="@Model.Name" />
			</div>
			<div class="form-group">
				<label>Mô tả</label>
				<input class="form-control" readonly value="@Model.Desc" />
			</div>
			<div class="form-group">
				<label asp-for="NewId">Vai trò thay thế</label>
				<select asp-for="NewId" class="form-control">
					<vc:list-role seleteted-id="null" exclude-ids="new int[] { Model.Id }"></vc:list-role>
				</select>
				<span asp-validation-for="NewId" class="text-danger"></span>
			</div>
		</div>

		<div class="col-md-8 col-xl-9">
			<h5>Có @Model.AppUsers.Count tài khoản bị ảnh hưởng</h5>
			<div class="row">
				@for (int i = 0; i < Model.AppUsers.Count; i++)
				{
					<div class="col-md-6 col-lg-4 col-xl-3">
						<p class="hover:text-primary text-bold">@(i+1). @Model.AppUsers[i].Username</p>
					</div>
				}
			</div>
		</div>

		<div class="col-12 text-center">
			<button type="button" class="btn btn-danger px-4 js-delete-confirm" data-mode="submit">
				<i class="fa fa-trash mr-2"></i> Xóa vai trò này
			</button>
		</div>
	</div>
</form>

<partial name="_BackToList" />

@section scripts{
	<script src="~/js/role/delete-role.js" asp-append-version="true"></script>
}

BaseProjectTemplate/App.Web/Views/Role/Edit.cshtml
@model App.Web.ViewModels.Role.RoleEditVM

@{
	ViewData["Title"] = $"Cập nhật vai trò [{Model.Name}]";
}

<form asp-action="Edit" method="post">
	<div class="row">
		<div class="col-md-12">
			<h5 class="my-3">Thông tin vai trò</h5>
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input asp-for="PermissionIds" class="fake-d-none" />
			<input asp-for="DeletedPermissionIds" class="fake-d-none" data-val="true" data-val-deleteAllPermission="@VM.RoleVM.PERMISSION_IDS_REQUIRED_ERR_MESG"/>
			<input asp-for="AddedPermissionIds" class="fake-d-none" />
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Name" class="control-label">Tên vai trò</label>
						<input asp-for="Name" class="form-control" />
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label asp-for="Desc" class="control-label">Mô tả</label>
						<input asp-for="Desc" class="form-control" />
						<span asp-validation-for="Desc" class="text-danger"></span>
					</div>
				</div>
			</div>
		</div>
		<div class="col-12 my-3">
			<h5>Các hành động được phép</h5>
			<span asp-validation-for="DeletedPermissionIds" class="text-danger"></span>
		</div>

		@await Component.InvokeAsync("Permission")
	</div>
	<div class="row">
		<div class="col">
			<div class="form-group">
				<button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Lưu</button>
				<button type="reset" class="btn btn-default"><i class="fa fa-undo"></i> Nhập lại</button>
			</div>
		</div>
	</div>
</form>

<partial name="_BackToList" />

@section scripts {
	<script src="~/lib/masonry/masonry.pkgd.min.js"></script>
	<script src="~/js/role/create-edit-role.js" asp-append-version="true"></script>
}

BaseProjectTemplate/App.Web/Views/Role/Index.cshtml
@model IEnumerable<App.Web.ViewModels.Role.RoleListItemVM>

@{
	ViewData["Title"] = "Danh sách vai trò";
}

@if (User.IsInPermission(AuthConst.AppRole.CREATE))
{
	<div class="my-2">
		<a asp-action="Create" class="btn btn-primary">
			<i class="fas fa-plus-circle"></i> &nbsp; Thêm mới vai trò
		</a>
	</div>
}

<div class="table-responsive">
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Tên quyền</th>
				<th>Mô tả</th>
				<th>Ngày tạo</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td class="fit">@item.RowIndex</td>
					<td>@Html.DisplayFor(modelItem => item.Name)</td>
					<td>@Html.DisplayFor(modelItem => item.Desc)</td>
					<td class="fit">@item.CreatedDate.ToDMYHM()</td>
					<td class="fit">
						<a href="#"
						   class="btn btn-outline-secondary btn-sm"><i class="fa fas fa-eye"></i></a>
						@if (User.IsInPermission(AuthConst.AppRole.UPDATE))
						{
							<a asp-action="Edit" asp-route-id="@item.Id"
							   class="btn btn-outline-secondary btn-sm"><i class="fa fas fa-pen"></i></a>
						}
						@if (User.IsInPermission(AuthConst.AppRole.DELETE))
						{
							<a asp-action="Delete" asp-route-id="@item.Id"
							   class="btn btn-outline-secondary btn-sm"><i class="fa fas fa-trash"></i></a>
						}
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

<partial name="_Pager" />