BaseProjectTemplate/App.Web/ViewModels/Account/ChangePassword.cs
using App.Web.WebConfig;
using App.Shared.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace App.Web.ViewModels.Account
{
	public class ChangePassword
	{
		[DataType(DataType.Password)]
		[AppRequired]
		public string Pwd { get; set; }

		[DataType(DataType.Password)]
		[AppRequired]
		[AppMinLength(VM.UserVM.PWD_MINLEN)]
		public string NewPwd { get; set; }

		[DataType(DataType.Password)]
		[AppConfirmPwd("NewPwd")]
		public string ConfirmPassword { get; set; }

		public bool LogoutAfterChangePwd { get; set; }
	}
}

BaseProjectTemplate/App.Web/Components/MainNavBar/MainNavBarViewComponent.cs
using App.Data.Entities;
using App.Data.Repositories;
using App.Share.Consts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace App.Web.Components.MainNavBar
{
	public class MainNavBarViewComponent : ViewComponent
	{
		readonly GenericRepository repository;
		public MainNavBarViewComponent(GenericRepository _repository)
		{
			repository = _repository;
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			var navBar = new NavBarViewModel();
			navBar.Items.AddRange(new MenuItem[]
			{
				new MenuItem
				{
					Action = "Index",
					Controller = "User",
					DisplayText = "Quản lý tài khoản",
					Icon = "fa-user-cog",
					Permission = AuthConst.AppUser.VIEW_LIST,
				},
				new MenuItem
				{
					Action = "Index",
					Controller = "Role",
					DisplayText = "Quản lý phân quyền",
					Icon = "fa-user-shield",
					Permission = AuthConst.AppRole.VIEW_LIST,
				},
				new MenuItem
				{
					Action = "Index",
					Controller = "FileManager",
					DisplayText = "Quản lý tệp",
					Icon = "fa-folder-open",
				},
				//new MenuItem
				//{
				//	DisplayText = "Menu 2 cấp",
				//	Icon = "fa-folder-open",
				//	ChildrenItems = new MenuItem[]
				//	{
				//		new MenuItem
				//		{
				//			Action = "Index",
				//			Controller = "User",
				//			DisplayText = "Quản lý tài khoản",
				//			Icon = "fa-user-cog"
				//		}
				//	}
				//},
			});
			return View(navBar);
		}
	}
}

BaseProjectTemplate/App.Web/Views/Shared/_BackToList.cshtml
<div>
	<a class="btn btn-link" asp-action="Index"><i class="fa fa-arrow-left"></i> Về trang danh sách</a>
</div>

BaseProjectTemplate/App.Web/Views/Shared/_ChangePassword.cshtml
@model App.Web.ViewModels.Account.ChangePassword
<div class="modal fade" id="mChangePassword" tabindex="-1" role="dialog" aria-labelledby="mChangePassword-label" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<h5 class="modal-title" id="mChangePasswordTitle">Đổi mật khẩu</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label asp-for="Pwd" class="control-label">Nhập lại mật khẩu</label>
						<input asp-for="Pwd" type="password" class="form-control" />
						<span asp-validation-for="Pwd" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="NewPwd" class="control-label">Mật khẩu mới</label>
						<input asp-for="NewPwd" type="password" class="form-control" />
						<span asp-validation-for="NewPwd" class="text-danger"></span>
					</div>
					<div class="form-group">
						<label asp-for="ConfirmPassword" class="control-label">Xác nhận mật khẩu mới</label>
						<input asp-for="ConfirmPassword" type="password" class="form-control" />
						<span asp-validation-for="ConfirmPassword" class="text-danger"></span>
					</div>
					<div class="form-check">
						<input class="form-check-input" checked id="remember" asp-for="LogoutAfterChangePwd" >
						<label class="form-check-label user-select-none" for="remember">
							Đăng xuất sau khi đổi mật khẩu
						</label>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary" asp-action="ChangePassword" asp-controller="Account"><i class="fas fa-key"></i> Đổi mật khẩu</button>
				</div>
			</form>
		</div>
	</div>
</div>

BaseProjectTemplate/App.Web/Views/Shared/_Export.cshtml
<div class="modal fade" id="mExport" tabindex="-1" role="dialog" aria-labelledby="mExport-label" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="mExportTitle">Chọn thời gian</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<!--Modal content-->
				<form asp-action="Export" method="post">
					<div class="form-group">
						<label for="from">Từ ngày</label>
						<input type="date" required name="FromDate" class="form-control" id="from" placeholder="Chọn ngày">
					</div>
					<div class="form-group">
						<label for="from">Đến ngày</label>
						<input type="date" required name="ToDate" class="form-control" id="from" placeholder="Chọn ngày">
					</div>
					<div class="form-group">
						<button class="btn btn-success"><i class="fas fa-file-download"></i>&ensp;Xuất Excel</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

BaseProjectTemplate/App.Web/Views/Shared/_HeaderBar.cshtml
@using System.Security.Claims
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
	<!-- Left navbar links -->
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
	</ul>

	<!-- Right navbar links -->
	<ul class="navbar-nav ml-auto">
		<li class="nav-item px-3">
			Xin chào @Context.User.Identity.Name
		</li>

		<li class="nav-item px-3">
			<a asp-action="Logout" asp-controller="Account">Đăng xuất</a>
		</li>
	</ul>
</nav>

BaseProjectTemplate/App.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@ViewBag.Title</title>
	<link rel="icon" type="image/x-icon" href="~/favicon.ico" asp-append-version="true"/>
	<!-- Google Font: Source Sans Pro -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="/adminLTE/plugins/fontawesome-free/css/all.min.css">
	<!-- Theme style -->
	<link rel="stylesheet" href="/adminLTE/dist/css/adminlte.min.css">

	<link href="~/lib/bs4-toast-snackbar/css/toast-snackbar.css" rel="stylesheet" asp-append-version="true"/>

	<link href="~/css/site.css" rel="stylesheet" asp-append-version="true"/>

	@RenderSection("head", false)
</head>
<body class="hold-transition sidebar-mini layout-fixed">
	<!-- Site wrapper -->
	<div class="wrapper">
		<partial name="_HeaderBar" />

		<vc:main-nav-bar></vc:main-nav-bar>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Main content -->
			<section class="content p-4">

				<partial name="_Noti" />

				<!-- Default box -->
				<div class="card">
					<div class="card-header">
						<h3 class="h3">@ViewBag.Title</h3>
					</div>
					<div class="card-body">
						@RenderBody()
					</div>
					<!-- /.card-body -->
				</div>
				<!-- /.card -->

			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->

		<footer class="main-footer">
			Project
		</footer>

	</div>
	<partial name="_ChangePassword" model="null" />
	<!-- ./wrapper -->
	<!-- jQuery -->
	<script src="/lib/jquery/dist/jquery.min.js"></script>
	<!-- Bootstrap 4 -->
	<script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<!-- Thư viện autocomplete -->
	<script src="~/lib/bs4-autocomplete/js/bs4-autocomplete.js" asp-append-version="true"></script>
	<!-- Thư viện toast-->
	<script src="~/lib/bs4-toast-snackbar/js/toast-snackbar.js" asp-append-version="true"></script>
	<!-- AdminLTE App -->
	<script src="/adminLTE/dist/js/adminlte.min.js"></script>
	<!-- Validation -->
	<partial name="_ValidationScriptsPartial" />
	<!-- Thư viện modal -->
	<script src="~/lib/bs4-modal/modal.js" asp-append-version="true"></script>
	<!-- Javascript dùng chung -->
	<script src="~/js/site.js" asp-append-version="true"></script>

	@RenderSection("scripts", false)
</body>
</html>

BaseProjectTemplate/App.Web/Views/Shared/_Noti.cshtml
@{
	var typeOfMesg = "";
	var mesg = "";
}
@if (TempData["Err"] != null)
{
	typeOfMesg = "danger";
	mesg = TempData["Err"].ToString();
}
else if (TempData["Success"] != null)
{
	typeOfMesg = "success";
	mesg = TempData["Success"].ToString();
}

@if (!typeOfMesg.IsNullOrEmpty())
{
	<div class="alert alert-@typeOfMesg alert-dismissible js-alert fade show" role="alert">
		@mesg
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
}

BaseProjectTemplate/App.Web/Views/Shared/_Pager.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@model IEnumerable<object>

@{
	string _params = "";
	foreach (var item in Context.Request.Query)
	{
		if (item.Key != "page")
		{
			_params += $"&{item.Key}={item.Value}";
		}
	}
}
<div class="my-4">
@Html.PagedListPager((IPagedList)Model,
	page => Url.Action("Index", new { page = page }) + _params,
	new PagedListRenderOptions
	{
		LiElementClasses = new string[] { "page-item" },
		PageClasses = new string[] { "page-link" },
	})
</div>